### ISSUE TITLE
Any example of WAI on HaLVM?

### ISSUE THREAD

**Issue by cies** [GaloisInc/HaLVM#43]
I'm curious if there are any obstacles from WAI being used on HaLVM.  I understand why Yesod would be problematic, but wonder if WAI would also be problematic or simply not yet done in a public repo that I can find.

Thanks!

**Comment by thumphries** [comment]
The only thing that seems immediately problematic to me is the `network` dependency. Swapping that out for `network-hans` will probably get you most of the way there.

WAI backends might be a problem. It looks like it would require some porting effort to get Warp running, since it uses some `unix` machinery that the HaLVM doesn't support, and probably expects a filesystem.

**Comment by cies** [comment]
Thanks for the quick reply!
