### ISSUE TITLE
Is there a way to skip building stage1 compiler?

### ISSUE THREAD

**Issue by gracjan** [GaloisInc/HaLVM#55]
Compiling all of this takes a lot of time.

Provided that platform GHC is decent (it is 7.8.4), is there a way to build stage2 directly?

**Comment by gracjan** [comment]
And is there a way to skip `profiling` libraries? Those also take pita amount of time to build.

**Comment by thumphries** [comment]
As far as I know, the stage1 is halvm-ghc, i.e. the main point of the build. Long builds are unavoidable.

For profiling, check out `src/misc/build.mk.in`. You can probably disable the 'p' way.
It would be nice to bury profiling behind a configure flag.

**Comment by acw** [comment]
Technically, the HaLVM is always a stage1 build, and never builds a stage2. However, I suspect what you want is the ability to skip the local version of GHC that the HaLVM build process creates in order to build the HaLVM cross-compiler.

In this case, yes, there is a very narrow set of cases in which we could skip it, but it's never been a high enough priority for us to put the checks in configure and the related Makefiles. Specifically, this will only work if the platform-installed version of GHC is identical to the one we're building for the HaLVM, and if the platform-installed version of GHC is compiled to use the same integer library you want to use with the HaLVM. The former is to make Template Haskell work, the latter is because GHC is a little silly with regard to integer libraries.

I'd be happy to take a pull request if you want to write up those tests, especially if you can find a nice, elegant way to do the test.

See also #15, which I think is an attempt to fix a number of issues, including this one.

With regard to the profiling libraries, yes, absolutely. I actually thought there was a configure option for that. I've add #58 to track this.

**Comment by gracjan** [comment]
If it does not build both stage1 and stage2 then I'm happy.
