### ISSUE TITLE
Api server in halvm

### ISSUE THREAD

**Issue by ruslantalpa** [GaloisInc/HaLVM#68]
Would it be possible (in the not so distant future) to have a project like this https://github.com/begriffs/postgrest compiled in halvm?
What would need to happen in halvm or postgrest?
currently postgrest links to these c libs
```
bash-3.2$ otool -L postgrest 
postgrest:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/Applications/Postgres.app/Contents/Versions/9.4/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.7.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.0.0)
```
probably the most important here is libpq.5.dylib

**Comment by acw** [comment]
Short answer: Well, maybe, but I doubt it.

Long answer:
Well, step one would be to start diving into what it would take to get all of these C libraries building on the HaLVM. I'm guessing libz wouldn't be too difficult, and I think I've already gotten parts of libiconv into the base HaLVM C libraries. The work here would be to add whatever functions and headers are necessary either to our existing minimal libc implementation (see GaloisInc/minlibc), or via some other mechanism.

You could probably get pretty far with that, but I think you'd run into problem actually using it. My memory of libpq -- which I will grant is about 10-12 years old -- is that it does a lot of networking, which the HaLVM doesn't support at the C level. So you might be able to get it to build, but you'd only be able to use libpq functions that didn't touch the network. (This is because our network card and network stack are written in Haskell, not C.)

We have a long term possible fix for this, but we're about 9 - 12 months out on it at this point.

**Comment by ruslantalpa** [comment]
Thank you, actually that's encouraging :), to me 9-12 months is the "not so distant future".
Worse case scenario, postrgesql binary protocol could be written in haskell ...:)
